2014-10-26 19:36:03,739 monitor.py[line:11] DEBUG test
2014-10-26 19:42:51,147 crawl.py[line:32] ERROR generic exception: Traceback (most recent call last):
  File "./crawl.py", line 19, in url_read
    content=urllib2.urlopen(req,timeout=60).read()
  File "/home/zhouqiang/.jumbo/lib/python2.7/socket.py", line 351, in read
    data = self._sock.recv(rbufsize)
  File "/home/zhouqiang/.jumbo/lib/python2.7/httplib.py", line 541, in read
    return self._read_chunked(amt)
  File "/home/zhouqiang/.jumbo/lib/python2.7/httplib.py", line 601, in _read_chunked
    value.append(self._safe_read(chunk_left))
  File "/home/zhouqiang/.jumbo/lib/python2.7/httplib.py", line 647, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/home/zhouqiang/.jumbo/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
timeout: timed out

2014-10-26 19:42:51,148 crawl.py[line:32] ERROR generic exception: Traceback (most recent call last):
  File "./crawl.py", line 19, in url_read
    content=urllib2.urlopen(req,timeout=60).read()
  File "/home/zhouqiang/.jumbo/lib/python2.7/socket.py", line 351, in read
    data = self._sock.recv(rbufsize)
  File "/home/zhouqiang/.jumbo/lib/python2.7/httplib.py", line 541, in read
    return self._read_chunked(amt)
  File "/home/zhouqiang/.jumbo/lib/python2.7/httplib.py", line 601, in _read_chunked
    value.append(self._safe_read(chunk_left))
  File "/home/zhouqiang/.jumbo/lib/python2.7/httplib.py", line 647, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/home/zhouqiang/.jumbo/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
timeout: timed out

2014-10-26 19:43:57,920 crawl.py[line:32] ERROR generic exception: Traceback (most recent call last):
  File "./crawl.py", line 19, in url_read
    content=urllib2.urlopen(req,timeout=60).read()
  File "/home/zhouqiang/.jumbo/lib/python2.7/socket.py", line 351, in read
    data = self._sock.recv(rbufsize)
  File "/home/zhouqiang/.jumbo/lib/python2.7/httplib.py", line 541, in read
    return self._read_chunked(amt)
  File "/home/zhouqiang/.jumbo/lib/python2.7/httplib.py", line 601, in _read_chunked
    value.append(self._safe_read(chunk_left))
  File "/home/zhouqiang/.jumbo/lib/python2.7/httplib.py", line 647, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/home/zhouqiang/.jumbo/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
timeout: timed out

